telegram_token: 247375230:AAGQq649NosnXkcyIgOiJ_EKpsSPYm3NBew
start_message: |
  Привет! Меня зовут ParterBot и я помогу тебе в подборе музыкального плейлиста.
  Введи /create <название> для создания плейлиста.
  Более подробно обо мне можно узнать, набрав команду /help.
help_message: |
  /create name - Создать плейлист с именем name. При вызове этой команды выпадает окно с настройками. Для генерации
  плейлиста необходимо нажать кнопку =сохранить=. Генерация плейлиста может занять некоторое время.
  /help - Помощь по использованию ParterBot.

names:
  - ['l', 'Количество треков']
  - ['g', 'Жанры']
  - ['e', 'Музыкальная эпоха']
  - ['t', 'Тематика']
  - ['s', 'СОХРАНИТЬ']

buttons:
  l:
    1 песня: 1
    2 песни: 2
    3 песни: 3
    4 песни: 4
    5 песен: 5
  g:
    Рок: 5258
    Chillout: 32321
    House: 32326
    Джаз: 31961
    Классическая: 904
  e:
    70-е: 144
    80-е: 145
    90-е: 23
    2000-е: 24
    2010-е: 25
  t:
    Романтика: 25739
    Утро: 32493
    Спорт: 22575
    Свобода: 25543
    Дорожный: 20225