telegram_token: 247375230:AAGQq649NosnXkcyIgOiJ_EKpsSPYm3NBew
start_message: |
  Привет! Используй клавиатуру ниже, чтобы вызывать команды.
  /create – создать плейлист
  /history – посмотреть, что слушал раньше
  /help – если нужна помощь

buttons:
  length:
    1 час: 1
    2 часа: 2
    3 часа: 3
    4 часа: 4
    5 часов: 5
    6 часов: 6
    7 часов: 7
    8 часов: 8
    9+ часов: 9
  genre:
    Рок: 5258
    Поп: 10
    Шансон: 2
    Джаз: 31961
    Классическая: 904
    Русская народная: 26086
  epoch:
    70-е: 144
    80-е: 145
    90-е: 23
    2000-е: 24
    2010-е: 25
  theme:
    Романтика: 25739
    Разлука: 26255
    Спорт: 22575
    Здоровье: 25938
    Застолье: 20255