telegram_token: 247375230:AAGQq649NosnXkcyIgOiJ_EKpsSPYm3NBew
start_message: |
  Привет! Используй клавиатуру ниже, чтобы вызывать команды.
  /create – создать плейлист
  /history – посмотреть, что слушал раньше
  /help – если нужна помощь

names:
  - ['l', 'Длительность плейлиста']
  - ['g', 'Жанры']
  - ['e', 'Музыкальная эпоха']
  - ['t', 'Тематика']
  - ['s', 'СОХРАНИТЬ']

buttons:
  l:
    1 песня: 1
    2 песни: 2
    3 песни: 3
    4 песни: 4
    5 песен: 5
    6 песен: 6
    7 песен: 7
    8 песен: 8
    9 песен: 9
    10 песен: 10
  g:
    Рок: 5258
    Поп: 10
    Шансон: 2
    Джаз: 31961
    Классическая: 904
    Русская народная: 26086
  e:
    70-е: 144
    80-е: 145
    90-е: 23
    2000-е: 24
    2010-е: 25
  t:
    Романтика: 25739
    Разлука: 26255
    Спорт: 22575
    Здоровье: 25938
    Застолье: 20255