telegram_token: 247375230:AAGQq649NosnXkcyIgOiJ_EKpsSPYm3NBew
start_message: |
  Привет! Меня зовут ParterBot и я помогу тебе в подборе музыкального плейлиста. Для этого необходимо
  ввести команду /create <название>. Подбери нужные параметры, и по ним я подберу тебе плейлист.
  Для того, чтобы просмотреть то, что слушал раньше можно ввести команду /history. Более подробно
  обо мне можно узнать, набрав команду /help.
help_message: |
  /create name - Создать плейлист с именем name. При вызове этой команды выпадает окно с настройками. Для генерации
  плейлиста необходимо нажать кнопку =сохранить=. Генерация плейлиста может занять некоторое время.
  /history id - История прослушивания. Отображает информацию о прослушанных плейлистов.
  /help - Помощь по использованию ParterBot.

buttons:
  length:
    1 час: 1
    2 часа: 2
    3 часа: 3
    4 часа: 4
    5 часов: 5
    6 часов: 6
    7 часов: 7
    8 часов: 8
    9+ часов: 9
  genre:
    Рок: 5258
    Поп: 10
    Шансон: 2
    Джаз: 31961
    Классическая: 904
    Русская народная: 26086
  epoch:
    70-е: 144
    80-е: 145
    90-е: 23
    2000-е: 24
    2010-е: 25
  theme:
    Романтика: 25739
    Разлука: 26255
    Спорт: 22575
    Здоровье: 25938
    Застолье: 20255